[build]
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"

# Ensure functions are bundled correctly
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

# Hourly cleanup schedule (runs sandbox-cleanup)
[[scheduled.functions]]
  name = "sandbox-cleanup"
  cron = "0 * * * *"

[[plugins]]
  package = "@netlify/plugin-nextjs"
